import pyautogui
import time

# Code to test the project cause lazy 

pyautogui.hotkey('alt','tab')
pyautogui.hotkey('ctrl','tab')
time.sleep(2)
pyautogui.PAUSE = 0.3

pyautogui.click(x=886, y=1048)
pyautogui.write('path')
pyautogui.press('enter')
# print(pyautogui.position())
time.sleep(2)
pyautogui.write('15')
pyautogui.press('enter')
pyautogui.write('36 12')
pyautogui.press('enter')


pyautogui.write('s f g f n f c n g e e s s w w p w o p k v u')
pyautogui.press('enter')
pyautogui.write('f y w t p f c n w e e s s w w p w o p k v g')
pyautogui.press('enter')
pyautogui.write('x f n t n f c b n t b s s g g p w o p k v d')
pyautogui.press('enter')
pyautogui.write('f y g t n f c b u t b s s w g p w o p k y d')
pyautogui.press('enter')
pyautogui.write('f y e t n f c b w t b s s g p p w o p n v d')
pyautogui.press('enter')
pyautogui.write('x s p f c f w n u e b s s w w p w o p k s d')
pyautogui.press('enter')
pyautogui.write('f s n t p f c n n e e s s w w p w o p k s g')
pyautogui.press('enter')
pyautogui.write('f f g t n f c b w t b s s p g p w o p n y d')
pyautogui.press('enter')
pyautogui.write('k y n f n f c n w e - k y w n p w o e w v d')
pyautogui.press('enter')
pyautogui.write('k s n f n a c b o e - s s o o p n o p n c l')
pyautogui.press('enter')
pyautogui.write('f y e t n f c b u t b s s w g p w o p n v d')
pyautogui.press('enter')
pyautogui.write('x s e f s f c n b t - k s w p p w o e w v l')
pyautogui.press('enter')
pyautogui.write('x f g f n f w b h t e f s w w p w o e k a g')
pyautogui.press('enter')
pyautogui.write('f s g t f f c b h t b s s w w p w o p h v u')
pyautogui.press('enter')
pyautogui.write('x y y t l f c b n e r s y w w p w o p n y g')
pyautogui.press('enter')
pyautogui.write('k y e f f f c n b t - k s p w p w o e w v d')
pyautogui.press('enter')
pyautogui.write('x f g t n f c b w t b s s w g p w o p k y d')
pyautogui.press('enter')
pyautogui.write('f s n f s f c n b t - s k p p p w o e w v l')
pyautogui.press('enter')
pyautogui.write('f y p t n f c b w e - s s w e p w t e w c w')
pyautogui.press('enter')
pyautogui.write('f y w t p f c n k e e s s w w p w o p n v u')
pyautogui.press('enter')
pyautogui.write('x s n t p f c n k e e s s w w p w o p k s u')
pyautogui.press('enter')
pyautogui.write('f f g t n f c b n t b s s g w p w o p k y d')
pyautogui.press('enter')
pyautogui.write('x y n t n f c b w e - s s w w p w t e w c w')
pyautogui.press('enter')
pyautogui.write('x y y t l f c b w e c s s w w p w o p n s g')
pyautogui.press('enter')
pyautogui.write('f y g f f f c b h e b k k p b p w o l h v d')
pyautogui.press('enter')
pyautogui.write('x f g t n f c b p t b s s p p p w o p k y d')
pyautogui.press('enter')
pyautogui.write('b f g f n f w b p e - s k w w p w t p w n g')
pyautogui.press('enter')
pyautogui.write('x s n t p f c n n e e s s w w p w o p k s g')
pyautogui.press('enter')
pyautogui.write('x s y t l f c b k e c s s w w p w o p k n m')
pyautogui.press('enter')
pyautogui.write('x y n f s f c n b t - s k w w p w o e w v l')
pyautogui.press('enter')
pyautogui.write('x f e t n f c b w t b s s p g p w o p k y d')
pyautogui.press('enter')
pyautogui.write('b s g f n f w b g e - k k w w p w t p w s g')
pyautogui.press('enter')
pyautogui.write('x s w t a f c b n e c s s w w p w o p k s g')
pyautogui.press('enter')
pyautogui.write('f y w f n f c n p e - s f w w p w o f h y d')
pyautogui.press('enter')
pyautogui.write('f y n f s f c n b t - s s w w p w o e w v p')
pyautogui.press('enter')
pyautogui.write('f f e t n f c b p t b s s p g p w o p k y d')
pyautogui.press('enter')

pyautogui.write('e')
pyautogui.press('enter')
pyautogui.write('p')
pyautogui.press('enter')
pyautogui.write('e')
pyautogui.press('enter')
pyautogui.write('e')
pyautogui.press('enter')
pyautogui.write('e')
pyautogui.press('enter')
pyautogui.write('p')
pyautogui.press('enter')
pyautogui.write('p')
pyautogui.press('enter')
pyautogui.write('e')
pyautogui.press('enter')
pyautogui.write('p')
pyautogui.press('enter')
pyautogui.write('e')
pyautogui.press('enter')
pyautogui.write('e')
pyautogui.press('enter')
pyautogui.write('p')
pyautogui.press('enter')
pyautogui.write('e')
pyautogui.press('enter')
pyautogui.write('p')
pyautogui.press('enter')
pyautogui.write('e')
pyautogui.press('enter')
pyautogui.write('p')
pyautogui.press('enter')
pyautogui.write('e')
pyautogui.press('enter')
pyautogui.write('p')
pyautogui.press('enter')
pyautogui.write('e')
pyautogui.press('enter')
pyautogui.write('p')
pyautogui.press('enter')
pyautogui.write('p')
pyautogui.press('enter')
pyautogui.write('e')
pyautogui.press('enter')
pyautogui.write('e')
pyautogui.press('enter')
pyautogui.write('e')
pyautogui.press('enter')
pyautogui.write('p')
pyautogui.press('enter')
pyautogui.write('e')
pyautogui.press('enter')
pyautogui.write('e')
pyautogui.press('enter')
pyautogui.write('p')
pyautogui.press('enter')
pyautogui.write('e')
pyautogui.press('enter')
pyautogui.write('p')
pyautogui.press('enter')
pyautogui.write('e')
pyautogui.press('enter')
pyautogui.write('e')
pyautogui.press('enter')
pyautogui.write('e')
pyautogui.press('enter')
pyautogui.write('e')
pyautogui.press('enter')
pyautogui.write('p')
pyautogui.press('enter')
pyautogui.write('e')
pyautogui.press('enter')

pyautogui.write('x s w f n f w b n t e f f w w p w o e k s g')
pyautogui.press('enter')
pyautogui.write('x f n t n f c b p t b s s w w p w o p k v d')
pyautogui.press('enter')
pyautogui.write('x s w t f f c b h t b f f w w p w o p h s g')
pyautogui.press('enter')
pyautogui.write('x f y f f f c b g e b k k p n p w o l h y p')
pyautogui.press('enter')
pyautogui.write('k f w f n f w b p e - k k w w p w t p w s g')
pyautogui.press('enter')
pyautogui.write('f y n f f f c n b t - s k w w p w o e w v p')
pyautogui.press('enter')
pyautogui.write('x y g f f f c b p e b k k p n p w o l h y g')
pyautogui.press('enter')
pyautogui.write('b f g f n f w b g e - k s w w p w t p w s g')
pyautogui.press('enter')
pyautogui.write('x y w t a f c b g e c s s w w p w o p n n g')
pyautogui.press('enter')
pyautogui.write('f y y f f f c b h e b k k p p p w o l h y g')
pyautogui.press('enter')
pyautogui.write('f y n t n f c b p t b s s w w p w o p k y d')
pyautogui.press('enter')
pyautogui.write('x s e f y f c n b t - s s w w p w o e w v p')
pyautogui.press('enter')