import pyautogui
import time

# Code to test the project cause lazy 

pyautogui.hotkey('alt','tab')
pyautogui.hotkey('ctrl','tab')
time.sleep(2)
pyautogui.PAUSE = 0.3

pyautogui.click(x=886, y=1048)
pyautogui.write('& C:/Users/Renan/AppData/Local/Programs/Python/Python312/python.exe "c:/Users/Renan/Desktop/Pasta_do_Renan_=)/Python/trampoEld/aux1.py"')
pyautogui.press('enter')
# print(pyautogui.position())
time.sleep(2)
pyautogui.write('1')
pyautogui.press('enter')
pyautogui.write('33 11')
pyautogui.press('enter')
pyautogui.write('f s g t f f c b w t b f s w w p w o p h v g')
pyautogui.press('enter')
pyautogui.write('x f g t n f c b p t b s s w w p w o p k y d')
pyautogui.press('enter')
pyautogui.write('f y n t n f c b u t b s s g w p w o p k y d')
pyautogui.press('enter')
pyautogui.write('x s y t l f c b k e c s s w w p w o p k s g')
pyautogui.press('enter')
pyautogui.write('b f w f n f w b g e - s s w w p w t p w s g')
pyautogui.press('enter')
pyautogui.write('s f n f n f c n g e e s s w w p w o p n v u')
pyautogui.press('enter')
pyautogui.write('x f g f n f w b g e - k s w w p w t p w s g')
pyautogui.press('enter')
pyautogui.write('x s w t p f c n p e e s s w w p w o p n v g')
pyautogui.press('enter')
pyautogui.write('f f e t n f c b p t b s s g g p w o p n v d')
pyautogui.press('enter')
pyautogui.write('f s b t n f c b e e - s s w e p w t e w c w')
pyautogui.press('enter')
pyautogui.write('f y n t l f c b n e r s y w w p w o p k y p')
pyautogui.press('enter')
pyautogui.write('x f g f c f c n n e b s s w w p w o p k v d')
pyautogui.press('enter')
pyautogui.write('x y g f f f c b h e b k k p b p w o l h y g')
pyautogui.press('enter')
pyautogui.write('f s b t f f c b p t b f f w w p w o p h s g')
pyautogui.press('enter')
pyautogui.write('k y n f y f c n b t - k s w w p w o e w v p')
pyautogui.press('enter')
pyautogui.write('f s b t f f c b p t b f f w w p w o p h v g')
pyautogui.press('enter')
pyautogui.write('x s w t p f c n n e e s s w w p w o p n v u')
pyautogui.press('enter')
pyautogui.write('f y y f f f c b g e b k k n b p w o l h y p')
pyautogui.press('enter')
pyautogui.write('s f n f n f c n g e e s s w w p w o p n y u')
pyautogui.press('enter')
pyautogui.write('x y e t n f c b u t b s s p w p w o p n y d')
pyautogui.press('enter')
pyautogui.write('f y p t n f c b g e b s s w w p w t p r v g')
pyautogui.press('enter')
pyautogui.write('f s e f f f c n b t - s s w w p w o e w v d')
pyautogui.press('enter')
pyautogui.write('x s b t n f c b e e - s s e e p w t e w c w')
pyautogui.press('enter')
pyautogui.write('x y g t n f c b u t b s s g w p w o p k v d')
pyautogui.press('enter')
pyautogui.write('x y y t a f c b n e r s y w w p w o p n s g')
pyautogui.press('enter')
pyautogui.write('f y y f f f c b g e b k k p n p w o l h y g')
pyautogui.press('enter')
pyautogui.write('f y n f y f c n b t - s s w p p w o e w v p')
pyautogui.press('enter')
pyautogui.write('x s b t f f c b p t b f s w w p w o p h v u')
pyautogui.press('enter')
pyautogui.write('f y n f n f c b w e b y y n n p w t p w y p')
pyautogui.press('enter')
pyautogui.write('x y n t a f c b n e r s y w w p w o p n s g')
pyautogui.press('enter')
pyautogui.write('f s g f n f w b n t e f f w w p w o e k s g')
pyautogui.press('enter')
pyautogui.write('f f g t n f c b w t b s s g w p w o p k y d')
pyautogui.press('enter')
pyautogui.write('x y e f y f c n b t - s s w w p w o e w v l')
pyautogui.press('enter')

pyautogui.write('p')
pyautogui.press('enter')
pyautogui.write('e')
pyautogui.press('enter')
pyautogui.write('e')
pyautogui.press('enter')
pyautogui.write('e')
pyautogui.press('enter')
pyautogui.write('e')
pyautogui.press('enter')
pyautogui.write('e')
pyautogui.press('enter')
pyautogui.write('e')
pyautogui.press('enter')
pyautogui.write('e')
pyautogui.press('enter')
pyautogui.write('p')
pyautogui.press('enter')
pyautogui.write('e')
pyautogui.press('enter')
pyautogui.write('e')
pyautogui.press('enter')
pyautogui.write('e')
pyautogui.press('enter')
pyautogui.write('p')
pyautogui.press('enter')
pyautogui.write('p')
pyautogui.press('enter')
pyautogui.write('p')
pyautogui.press('enter')
pyautogui.write('p')
pyautogui.press('enter')
pyautogui.write('p')
pyautogui.press('enter')
pyautogui.write('p')
pyautogui.press('enter')
pyautogui.write('p')
pyautogui.press('enter')
pyautogui.write('e')
pyautogui.press('enter')
pyautogui.write('e')
pyautogui.press('enter')
pyautogui.write('p')
pyautogui.press('enter')
pyautogui.write('p')
pyautogui.press('enter')
pyautogui.write('e')
pyautogui.press('enter')
pyautogui.write('e')
pyautogui.press('enter')
pyautogui.write('e')
pyautogui.press('enter')
pyautogui.write('p')
pyautogui.press('enter')
pyautogui.write('p')
pyautogui.press('enter')
pyautogui.write('p')
pyautogui.press('enter')
pyautogui.write('e')
pyautogui.press('enter')
pyautogui.write('e')
pyautogui.press('enter')
pyautogui.write('e')
pyautogui.press('enter')
pyautogui.write('e')
pyautogui.press('enter')

pyautogui.write('f f g f f f c b p e b k k n b p w o l h v d')
pyautogui.press('enter')
pyautogui.write('b s y t l f c b w e c s s w w p w o p k n g')
pyautogui.press('enter')
pyautogui.write('f f n t n f c b n t b s s w w p w o p n y d')
pyautogui.press('enter')
pyautogui.write('x s w t a f w n p t b s s w w p w o p u v d')
pyautogui.press('enter')
pyautogui.write('k y n f f f c n b t - k k p p p w o e w v l')
pyautogui.press('enter')
pyautogui.write('f y e f s f c n b t - s s w w p w o e w v p')
pyautogui.press('enter')
pyautogui.write('x y e t n f c b u t b s s p g p w o p k v d')
pyautogui.press('enter')
pyautogui.write('f f n t n f c b p t b s s w w p w o p k y d')
pyautogui.press('enter')
pyautogui.write('x s n t p f c n k e e s s w w p w o p n s u')
pyautogui.press('enter')
pyautogui.write('f y w t p f c n w e e s s w w p w o p k s u')
pyautogui.press('enter')
pyautogui.write('x f n t n f c b u t b s s w g p w o p k v d')
pyautogui.press('enter')